:toc: macro
:toc-title: Summary
:toclevels: 3
:numbered:

ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

:back_to_top_target: top-target
:back_to_top_label: ⬆ Back to top
:back_to_top: <<{back_to_top_target},{back_to_top_label}>>

:main_title: Resistor Color Code Calculator
:git_project: resistor-color-code-calculator
:git_username: jprivet-dev
:git_url: https://github.com/{git_username}/{git_project}
:git_clone_ssh: git@github.com:{git_username}/{git_project}.git

// Releases
:project_release: v0.1.0
:angular_release: 16.1.8

[#{back_to_top_target}]
= {main_title}

image:https://badgen.net/badge/release/{project_release}/blue[Project release,link={git_url}/releases/tag/{project_release}]
image:https://badgen.net/badge/angular/{angular_release}/d93630[Angular release,link=https://github.com/angular/angular/releases/tag/{angular_release}]

toc::[]

== Presentation

Tool to calculate the characteristics of various resistors.

{back_to_top}

== Installation

. `$ git clone {git_clone_ssh}`
. `$ cd {git_project}`
. `$ npm install`
. `$ ng serve`
. Open your browser on http://localhost:4200/.

{back_to_top}

== Memento Angular

=== Development server

Run `ng serve` for a dev server. Navigate to `http://localhost:4200/`. The application will automatically reload if you change any of the source files.

=== Code scaffolding

Run `ng generate component component-name` to generate a new component. You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module`.

=== Build

Run `ng build` to build the project. The build artifacts will be stored in the `dist/` directory.

=== Running unit tests

Run `ng test` to execute the unit tests via https://karma-runner.github.io[Karma].

=== Running end-to-end tests

Run `ng e2e` to execute the end-to-end tests via a platform of your choice. To use this command, you need to first add a package that implements end-to-end testing capabilities.

=== Further help

To get more help on the Angular CLI use `ng help` or go check out the https://angular.io/cli[Angular CLI Overview and Command Reference] page.

{back_to_top}

== Resources

* https://angular.io
* https://ngrx.io
* https://getbootstrap.com
* https://ng-bootstrap.github.io
* https://ngneat.github.io/transloco

{back_to_top}

== Comments, suggestions?

Feel free to make comments/suggestions to me in the {git_url}/issues[Git issues section].

{back_to_top}

== License

"{main_title}" is released under the {git_url}/blob/main/LICENSE[*MIT License*].

---

{back_to_top}
